### ISSUE TITLE
Install questions

### ISSUE THREAD

**Issue by leiyangleon** [leiyangleon/FSH#1]

**Comment by leiyangleon** [comment]
It works!

**Comment by leiyangleon** [comment]
TEST!

**Comment by leiyangleon** [comment]
test!

**Comment by bextla20** [comment]
Hi

l faced problem install Forest Stand Height (FSH) Python Scripts. Some script is not in Anaconda. could you please explain how to install and use. 
l view  this link (https://github.com/leiyangleon/FSH) but, it is confused. And as l know there must be **test_example_ISCE_stripmapApp** folder, but it hasn't.

Regards
Bakhtiyar

**Comment by leiyangleon** [comment]
> Hi
> 
> l faced problem install Forest Stand Height (FSH) Python Scripts. Some script is not in Anaconda. could you please explain how to install and use.
> l view this link (https://github.com/leiyangleon/FSH) but, it is confused. And as l know there must be **test_example_ISCE_stripmapApp** folder, but it hasn't.
> 
> Regards
> Bakhtiyar

Please post the actual install problem you encountered. In fact, there is no need to install FSH, which is just a folder of Python scripts. You can download the folder of scripts to your local directory and run the code from there.

In the [web link of FSH](https://github.com/leiyangleon/FSH), 

- click on the hyperlink of Section 1 - Installation, to install the required packages which can be installed using Anaconda, pip or MacPorts depending on your operating system.

- click on the hyperlink of Section 2 - How to use, to learn how to run the code. **Again, note there is no need to install FSH. Users only need to install the required packages in Section 1.**

- click on the hyperlink "test_example_ISCE_stripmapApp" under Section 2, it will direct you to the specific page where the first line shows the link to download the dataset.

**Comment by bextla20** [comment]
Thank you for your answer. is it important all Python modules have to. how may l sure l have they, So Anaconda does not have simplekml and OsGeo/GDAL. l download simplekml by cmd, but l am not sure it download correct or not.
There mentioned Users only need to install the required packages in Section 1. in this case how may run script and which l need?
There are some scripts and it confused me.

l will be grateful if there is PDF for running all process.

**Comment by leiyangleon** [comment]
@bextla20 the GitHub page should be self-explanatory. It seems your questions relate to the computer skills and installation of software packages (dependency for FSH) rather than the FSH code itself and the ISCE preprocessing scripts either. If you find it insufficient and prefer pdf documentation, [here](https://gis1.servirglobal.net/TrainingMaterials/SAR/Chp4_appendixC.pdf) is one. Not sure if this one is better. But you can try. Again I would recommend you go through the docs on the GitHub page first.
