### ISSUE TITLE
TypeError in line 51 of remove_nonforest.py

### ISSUE THREAD

**Issue by hbparache** [leiyangleon/FSH#2]
Hi, I have accounted the TypeError "slice indices must be integers or None or have an __index__method" in line 51 of remove_nonforest.py while running through the example ROI_PAC dataset. Any assistance would be appreciated. I have attached a screenshot and please let me know if additional information would be helpful. 

![TypeError_Screenshot](https://user-images.githubusercontent.com/49163135/55342838-52470580-546f-11e9-9c5a-47eddd446069.png)

**Comment by leiyangleon** [comment]
This type of problems are due to recent update of Numpy and have already been fixed in the updated scripts.
