### ISSUE TITLE
Output Formats

### ISSUE THREAD

**Issue by hbparache** [leiyangleon/FSH#3]
I was able to successfully run the FSH scripts! Thank you for your assistance. One thing I wanted to clarify is, based on the readme I expected to get json, gif, tif, and mat outputs. I only have mat and json outputs (screenshot attached). Do you have any insight into this? Thanks!
![FSH_output_04_05](https://user-images.githubusercontent.com/49163135/55733054-ba06ce80-59e2-11e9-8644-c98cf39e4a28.PNG)

**Comment by leiyangleon** [comment]
The output file description is discussed in the README file. See below

_**"The location of the output files depends on whether they are related to the overall processing of the entire data set, or are directly associated with a single scene. Examples of each would be the SC iteration files as a general output, and a single forest stand height image as a scene-specific output. The general outputs will be stored in a directory named "output" located within the main file directory (file_directory). The scene specific outputs will be stored with the other scene data as described earlier."**_

This means the files in the "output" folder you are showing here are general output files, while the forest height maps in the format of "json, gif, tif, mat" you are expecting are scene-specific files, which are located under each scene folder. For example, you could see the corresponding height maps under "f890_o119", "f890_o118" and "f890_o120", respectively.

**Comment by hbparache** [comment]
Perfect, thank you!
