### ISSUE TITLE
Error “TypeError: ‘numpy.float64’ object cannot be interpreted as an index” 

### ISSUE THREAD

**Issue by hbparache** [leiyangleon/FSH#4]
Error “TypeError: ‘numpy.float64’ object cannot be interpreted as an index” when running the Forest Stand Height scripts on the example dataset pre-processed by ISCE.
<img width="395" alt="ISCE_Example_Error" src="https://user-images.githubusercontent.com/49163135/64571729-60585680-d32a-11e9-8d42-b3bbac550296.PNG">
 Screenshot attached

**Comment by leiyangleon** [comment]
We believe that the updated scripts (try downloading the most recent version) will eliminate this type of error as others had reported it before. Let me know if it fails again.

**Comment by hbparache** [comment]
Hi, I deleted all files and redownloaded this morning to make sure that I wasn't accidentally grabbing from old files when I tried this yesterday and the same error is still being thrown.

**Comment by leiyangleon** [comment]
Yes, there was a problem in converting the float to integer data type. Just updated the file. Try downloading the new "auto_tree_height_single_ISCE.py" and it should work now.

**Comment by hbparache** [comment]
The example data set works! Thank you so much. Will try it with my own data today.
